import { FlowSchema } from '../../types';

export const needsDiscoveryFlowSchema: FlowSchema = {
  name: 'ChocoAI Needs Discovery Flow',
  slug: 'needsDiscovery',
  description: 'Insurance intake: identify the insured business and clarify coverage needs',
  version: 1,
  definition: {
    stages: {
      identifyCustomer: {
        name: 'Identify customer',
        description: 'Identify the insured business (and only ask contact details if missing).',
        prompt: [
          'LANGUAGE: Maintain same language throughout. Hebrew → Hebrew. English → English.',
          '',
          'You are Choco (שוקו), an insurance broker.',
          'Goal: identify the insured business so we can start a quote.',
          '',
          'Be simple and clear.',
          'Prefer ONE short question.',
          'Use a numbered list (1., 2., 3., ...) ONLY when you ask for multiple items from different categories, or when the question would otherwise be long.',
          'Do NOT re-ask first/last/phone/email if already collected earlier in the conversation.',
          '',
          'CRITICAL COPY RULE (MUST FOLLOW):',
          '- When asking for these missing fields, use EXACTLY this Hebrew question (or extremely close, but keep it short and direct):',
          '  "מעולה, מה שם בית העסק, מספר חברה או מספר עוסק מורשה?"',
          '- Do NOT use phrasing like: "רק חסר לי", "כדי להתקדם", "תוכל לשלוח לי", "סוג תעודת זהות (ח\\"פ / ע\\"מ / ת\\"ז)".',
          '- If the user answers with multiple details in one message, accept all of them and continue.',
          '- If legal_id is already present (the user sent the number earlier), do NOT ask for the number again. Ask only for what is missing (usually: business_name + whether it is ע"מ/ח"פ).',
          '',
          'Collect (only what is missing):',
          '- business_name (שם בית העסק)',
          '- legal_id_type + legal_id (מספר חברה / עוסק מורשה / ת"ז)',
          '',
          'If needed, accept also ת"ז.',
          '',
          'If the user provides multiple details at once, accept all of them and move forward.',
        ].join('\n'),
        fieldsToCollect: [
          'business_name',
          'legal_id_type',
          'legal_id',
        ],
        nextStage: 'enrichBusiness',
      },
      enrichBusiness: {
        name: 'Enrich business data',
        description: 'Auto-enrich business details from external registries (silent).',
        fieldsToCollect: [],
        action: {
          toolName: 'insurance.enrichBusiness',
          condition: 'true',
          allowReExecutionOnError: true,
          onError: { behavior: 'continue' },
        },
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'This stage runs silently to enrich business data (e.g., by ח"פ lookup).',
        ].join('\n'),
        nextStage: 'productLine',
      },
      productLine: {
        name: 'Product line',
        description: 'Set a safe default product_line silently (no user question).',
        fieldsToCollect: [],
        action: {
          toolName: 'insurance.setDefaultProductLine',
          condition: 'true',
          allowReExecutionOnError: true,
          onError: { behavior: 'continue' },
        },
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'This stage runs silently to set a default product_line without confusing the user.',
        ].join('\n'),
        nextStage: 'businessProfile',
      },
      businessProfile: {
        name: 'Business profile',
        description: 'Collect what the business does (plain language).',
        prompt: [
          'You are Choco (שוקו). Keep it simple.',
          'Ask only what is missing.',
          '',
          'מה תחום/סוג העסק ומה התיאור הכי קצר של הפעילות?',
        ].join('\n'),
        fieldsToCollect: ['industry', 'activity_description'],
        nextStage: 'resolveSegment',
      },
      resolveSegment: {
        name: 'Resolve segment',
        description: 'Resolve segment/group and apply non-destructive defaults (silent).',
        fieldsToCollect: [],
        action: {
          toolName: 'insurance.resolveSegment',
          condition: 'true',
          allowReExecutionOnError: true,
          onError: { behavior: 'continue' },
        },
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'This stage runs silently to infer segment defaults.',
        ].join('\n'),
        nextStage: 'businessSize',
      },
      businessSize: {
        name: 'Business size',
        description: 'Collect minimal size indicators used for underwriting (plain language).',
        prompt: [
          'You are Choco (שוקו). Keep it short.',
          'Ask only what is missing.',
          '',
          'כמה עובדים יש בעסק ומה המחזור השנתי המשוער (בערך) בש״ח?',
        ].join('\n'),
        fieldsToCollect: ['employees_count', 'annual_turnover_ils'],
        nextStage: 'coverageNeeds',
      },
      coverageNeeds: {
        name: 'Coverage needs',
        description: 'Collect what they want to insure (plain language).',
        prompt: [
          'You are Choco (שוקו). The customer is not an insurance expert.',
          'Ask only what is missing.',
          '',
          'מה תרצה לבטח? (למשל תכולה/מלאי/צד ג׳/חבות מעבידים/אחריות מקצועית/סייבר) והאם יש דגשים מיוחדים?',
        ].join('\n'),
        fieldsToCollect: ['coverages_needed', 'special_risks'],
        nextStage: {
          conditional: [
            { condition: 'product_line === "med_pi"', ifTrue: 'medPiProfile' },
            { condition: 'product_line === "cyber"', ifTrue: 'cyberProfile' },
          ],
          fallback: 'ensureCase',
        },
      },
      medPiProfile: {
        name: 'Med PI profile',
        description: 'Collect a minimal professional profile for therapists / para-medical PI (plain language).',
        prompt: [
          'You are Choco (שוקו), an insurance broker specialized in therapists and para-medical professions.',
          'The customer is not an insurance expert; keep it simple.',
          '',
          'Ask ONLY for what is missing. Prefer ONE short question.',
          'Use a numbered list ONLY if the question would otherwise be long.',
          '',
          'Collect:',
          '- med_pi_profession (מה תחום הטיפול/המקצוע?)',
          '- med_pi_years_experience (כמה שנות ניסיון בערך?)',
          '- med_pi_licensed (יש רישיון/תעודה מקצועית? כן/לא)',
          '- med_pi_works_with_children (מטפל/ת בילדים? כן/לא)',
          '- med_pi_sessions_per_week (כמה מפגשים בערך בשבוע?)',
          '',
          'If they ask why: explain in 1 short sentence: "כדי להתאים כיסוי וסכום ביטוח."',
        ].join('\n'),
        fieldsToCollect: [
          'med_pi_profession',
          'med_pi_years_experience',
          'med_pi_licensed',
          'med_pi_works_with_children',
          'med_pi_sessions_per_week',
        ],
        nextStage: 'ensureCase',
      },
      cyberProfile: {
        name: 'Cyber profile',
        description: 'Collect minimal cyber risk questions (plain language) to support cyber annex.',
        prompt: [
          'You are Choco (שוקו). Keep it simple and non-technical.',
          '',
          'Ask ONLY for what is missing. Prefer ONE short question.',
          'Use a numbered list ONLY if the question would otherwise be long.',
          '',
          'Collect (yes/no where possible):',
          '- cyber_backups_exist (יש גיבוי למחשבים/מערכות?)',
          '- cyber_backup_frequency (אם יש — כל כמה זמן? יומי/שבועי/אחר)',
          '- cyber_antivirus_installed (יש אנטי־וירוס מעודכן?)',
          '- cyber_firewall_installed (יש פיירוול/הגנה ברשת?)',
          '- cyber_incident_last_5_years (היה אירוע סייבר/דלף מידע ב־5 השנים האחרונות? כן/לא)',
          '',
          'If incident=yes, ask for one short sentence details next.',
        ].join('\n'),
        fieldsToCollect: [
          'cyber_backups_exist',
          'cyber_backup_frequency',
          'cyber_backup_frequency_other',
          'cyber_antivirus_installed',
          'cyber_firewall_installed',
          'cyber_incident_last_5_years',
          'cyber_incident_last_5_years_details',
        ],
        orchestration: {
          // Allow completing without "other" unless backup_frequency === "other"
          customCompletionCheck: {
            condition: 'cyber_backup_frequency !== "other"',
            requiredFields: [
              'cyber_backups_exist',
              'cyber_backup_frequency',
              'cyber_antivirus_installed',
              'cyber_firewall_installed',
              'cyber_incident_last_5_years',
            ],
          },
        },
        nextStage: 'ensureCase',
      },
      ensureCase: {
        name: 'Create insurance case',
        description: 'Create or attach an InsuranceCase for this conversation.',
        fieldsToCollect: [],
        action: {
          toolName: 'insurance.ensureCase',
          condition: 'true',
          allowReExecutionOnError: true,
          onError: {
            behavior: 'pause',
            message: 'יש תקלה זמנית בפתיחת תיק הביטוח. אפשר לנסות שוב בעוד רגע.',
          },
        },
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'This stage runs silently to create/link an InsuranceCase.',
        ].join('\n'),
        nextStage: 'handoffToProposalForm',
      },
      handoffToProposalForm: {
        name: 'Handoff to proposal form',
        description: 'Seamlessly transition to proposalForm (dynamic questionnaire).',
        fieldsToCollect: [],
        action: {
          toolName: 'insurance.handoffToProposalForm',
          condition: 'true',
          allowReExecutionOnError: true,
          onError: {
            behavior: 'pause',
            message: 'יש תקלה זמנית בהמשך השאלון. אפשר לנסות שוב בעוד רגע.',
          },
        },
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'This stage runs silently to transition to proposalForm.',
        ].join('\n'),
      },
    },
    fields: {
      business_name: {
        type: 'string',
        description: 'שם בית העסק.',
        minLength: 1,
      },
      legal_id_type: {
        type: 'string',
        enum: ['HP', 'AM', 'TZ', 'EIN'],
        description: 'סוג מספר הזדהות (ח"פ / ע"מ / ת"ז).',
      },
      legal_id: {
        type: 'string',
        description: 'מספר חברה / עוסק מורשה / ת"ז (רק ספרות).',
        minLength: 4,
      },
      first_name: {
        type: 'string',
        description: 'Contact person first name.',
        minLength: 1,
      },
      last_name: {
        type: 'string',
        description: 'Contact person last name.',
        minLength: 1,
      },
      phone: {
        type: 'string',
        description: 'Contact mobile number (Israeli mobile preferred).',
      },
      email: {
        type: 'string',
        description: 'Contact email address.',
      },
      product_line: {
        type: 'string',
        enum: ['business_package', 'cyber', 'med_pi'],
        description: 'Requested product line (high level).',
      },
      coverages_needed: {
        type: 'string',
        description: 'Coverage modules requested (free text).',
      },
      special_risks: {
        type: 'string',
        description: 'Special risks / special clauses requested (free text).',
      },
      industry: {
        type: 'string',
        description: 'Business industry / type (SMB).',
      },
      activity_description: {
        type: 'string',
        description: 'Short description of business activity.',
      },
      annual_turnover_ils: {
        type: 'number',
        description: 'Estimated annual turnover in ILS.',
      },
      employees_count: {
        type: 'number',
        description: 'Number of employees.',
      },
      // Med PI (therapists / para-medical)
      med_pi_profession: {
        type: 'string',
        description: 'Med PI: profession / therapy field.',
      },
      med_pi_years_experience: {
        type: 'number',
        description: 'Med PI: years of experience (approx).',
      },
      med_pi_licensed: {
        type: 'boolean',
        description: 'Med PI: has a professional license/certificate.',
      },
      med_pi_works_with_children: {
        type: 'boolean',
        description: 'Med PI: works with children.',
      },
      med_pi_sessions_per_week: {
        type: 'number',
        description: 'Med PI: approximate sessions per week.',
      },
      // Cyber annex (minimal)
      cyber_backups_exist: {
        type: 'boolean',
        description: 'Cyber: backups exist.',
      },
      cyber_backup_frequency: {
        type: 'string',
        enum: ['daily', 'every_2_days', 'weekly', 'biweekly', 'other'],
        description: 'Cyber: backup frequency (enum).',
      },
      cyber_backup_frequency_other: {
        type: 'string',
        description: 'Cyber: backup frequency other (free text).',
      },
      cyber_antivirus_installed: {
        type: 'boolean',
        description: 'Cyber: antivirus installed.',
      },
      cyber_firewall_installed: {
        type: 'boolean',
        description: 'Cyber: firewall installed.',
      },
      cyber_incident_last_5_years: {
        type: 'boolean',
        description: 'Cyber: had security breach/data event in last 5 years.',
      },
      cyber_incident_last_5_years_details: {
        type: 'string',
        description: 'Cyber: short incident details (if yes).',
      },
    },
    config: {
      initialStage: 'identifyCustomer',
      onComplete: {
        startFlowSlug: 'proposalForm',
        mode: 'seamless',
        preserveFields: [
          'business_name',
          'legal_id_type',
          'legal_id',
          'first_name',
          'last_name',
          'phone',
          'email',
          'product_line',
          'coverages_needed',
          'special_risks',
          'industry',
          'activity_description',
          'annual_turnover_ils',
          'employees_count',
          'already_registered',
          // product-specific extras
          'med_pi_profession',
          'med_pi_years_experience',
          'med_pi_licensed',
          'med_pi_works_with_children',
          'med_pi_sessions_per_week',
          'cyber_backups_exist',
          'cyber_backup_frequency',
          'cyber_backup_frequency_other',
          'cyber_antivirus_installed',
          'cyber_firewall_installed',
          'cyber_incident_last_5_years',
          'cyber_incident_last_5_years_details',
          // Segmentation / defaults
          'segment_description',
          'segment_group_id',
          'segment_id',
          'default_package_key',
          'segment_name_he',
          'segment_group_name_he',
          'segment_resolution_source',
          'segment_resolution_confidence',
          // Questionnaire prefill vars (when inferred early)
          'has_physical_premises',
          'business_site_type',
          'business_site_type_other',
          'business_used_for',
          'business_activity_and_products',
        ],
      },
    },
  },
};

