import { FlowSchema } from '../../types';

export const proposalFormFlowSchema: FlowSchema = {
  name: 'ChocoAI Proposal Form Flow',
  slug: 'proposalForm',
  description: 'Collect proposal details and generate carrier PDF forms (MVP)',
  version: 2,
  definition: {
    stages: {
      routeByProduct: {
        name: 'Route by product',
        description: 'Internal routing stage based on product_line.',
        fieldsToCollect: [],
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'Route to the appropriate proposal steps based on product_line.',
        ].join('\n'),
        nextStage: {
          conditional: [
            { condition: 'product_line === "med_pi"', ifTrue: 'medPiBasics' },
            { condition: 'product_line === "cyber"', ifTrue: 'cyberBasics' },
          ],
          fallback: 'smartQuestionnaireInit',
        },
      },
      smartQuestionnaireInit: {
        name: 'Smart questionnaire (init)',
        description: 'Initialize Clal SMB dynamic questionnaire state and select the next relevant question.',
        fieldsToCollect: [],
        action: {
          toolName: 'insurance.questionnaire.init',
          condition: 'true',
          allowReExecutionOnError: true,
          onError: {
            behavior: 'pause',
            message: 'יש תקלה זמנית בפתיחת השאלון. אפשר לנסות שוב בעוד רגע.',
          },
        },
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'This stage runs silently to initialize the dynamic questionnaire.',
        ].join('\n'),
        nextStage: 'smartQuestionnaireAsk',
      },
      smartQuestionnaireAsk: {
        name: 'Smart questionnaire (ask)',
        description: 'Ask the next relevant questionnaire question and save the answer to insured_form_json via json_path.',
        prompt: [
          'LANGUAGE: Maintain same language throughout. Hebrew → Hebrew. English → English.',
          '',
          'You are Choco (שוקו), an insurance broker. Keep it short and human.',
          'Ask ONE question only. Do not add justification or extra steps.',
          '',
          'If questionnaire_stage_intro_to_send is present (non-empty), prepend it (up to 1-3 short sentences / short lines), then ask the question.',
          '',
          'You MUST ask EXACTLY this question:',
          '{questionnaire_prompt_he}',
          '',
          'If there are options, present them as short choices (no explanation): {questionnaire_options_he}',
          '',
          'CRITICAL (for extraction): Treat the user reply as the answer to this question. Do NOT change topics.',
        ].join('\n'),
        // IMPORTANT: Do NOT rely on LLM field extraction for questionnaire answers.
        // The questionnaireAnswer tool reads the last user message directly as the answer source of truth.
        // Keeping this empty prevents "stage completed" ACK-only behavior and makes the flow robust to extraction misses.
        fieldsToCollect: [],
        action: {
          toolName: 'insurance.questionnaire.answer',
          condition: 'true',
          allowReExecutionOnError: true,
          onError: {
            behavior: 'pause',
            message: 'לא הבנתי. אפשר לענות שוב בקצרה?',
          },
        },
        nextStage: {
          conditional: [
            { condition: 'handoff_required === true', ifTrue: 'handoffToUnderwriter' },
            { condition: 'questionnaire_complete === true', ifTrue: 'saveIntake' },
          ],
          fallback: 'smartQuestionnaireAsk',
        },
      },
      handoffToUnderwriter: {
        name: 'Handoff to underwriter',
        description: 'When risk signals require human underwriting review, pause automation and route to UW.',
        fieldsToCollect: [],
        prompt: [
          'LANGUAGE: Maintain same language throughout. Hebrew → Hebrew. English → English.',
          '',
          'You are Choco (שוקו), an insurance broker.',
          'Explain briefly (1-2 sentences) that we need an underwriter/human to review before proceeding.',
          'Do NOT mention internal rules or IDs.',
          '',
          'Hebrew example:',
          '"תודה — כדי להתקדם עם ההצעה צריך בדיקה קצרה של חתם/נציג אנושי בגלל פרט אחד או יותר שעלה. אני מעביר/ה את זה לבדיקה וחוזר/ת אליך בהקדם."',
        ].join('\n'),
        nextStage: 'handoffToUnderwriter',
      },
      businessAndTerm: {
        name: 'Business + policy term',
        description: 'Collect business classification and policy term basics for the proposal form.',
        prompt: [
          'LANGUAGE: Maintain same language throughout. Hebrew → Hebrew. English → English.',
          '',
          'You are Choco (שוקו), a senior insurance broker.',
          'The customer is NOT an insurance expert. Use simple words, no jargon.',
          '',
          'Ask ONLY for what is missing. Prefer ONE short question.',
          'Use a numbered list ONLY when the question would otherwise be long.',
          '',
          'Collect (only what is missing):',
          '- policy_term_start_date (מתי להתחיל את הביטוח?)',
          '- business_legal_entity_type (סוג התאגדות: עוסק מורשה/חברה/שותפות/אחר)',
          '- business_type (סוג מקום: משרד/חנות/מחסן/סדנה/מפעל/אחר)',
          '- business_type_other (רק אם "אחר")',
          '',
          'If the user is unsure, offer a simple choice and proceed with a reasonable default.',
        ].join('\n'),
        orchestration: {
          // Allow completing this stage without business_type_other unless business_type === "other"
          customCompletionCheck: {
            condition: 'business_type !== "other"',
            requiredFields: ['policy_term_start_date', 'business_legal_entity_type', 'business_type'],
          },
        },
        fieldsToCollect: [
          'policy_term_start_date',
          'business_legal_entity_type',
          'business_type',
          'business_type_other',
        ],
        nextStage: 'businessAddress',
      },
      cyberBasics: {
        name: 'Cyber proposal (basics)',
        description: 'Collect minimal data to issue a cyber proposal (customer-friendly).',
        prompt: [
          'LANGUAGE: Maintain same language throughout. Hebrew → Hebrew. English → English.',
          '',
          'You are Choco (שוקו). The customer is NOT an insurance expert.',
          'Keep it simple and short.',
          '',
          'Ask ONLY for what is missing.',
          '',
          'Collect:',
          '- policy_term_start_date (מתי להתחיל את הביטוח?)',
          '- cyber_limit_per_claim_and_period_ils (סכום כיסוי סייבר לשנה/לתביעה; אם לא בטוחים אפשר "סטנדרט")',
          '',
          'Then ask 2-3 quick yes/no security questions (one per message): backups, antivirus, firewall.',
        ].join('\n'),
        fieldsToCollect: ['policy_term_start_date', 'cyber_limit_per_claim_and_period_ils'],
        nextStage: 'cyberSecurity',
      },
      cyberSecurity: {
        name: 'Cyber security',
        description: 'Map to annex_a_cyber.system_security',
        prompt: [
          'You are Choco (שוקו). Keep it simple.',
          'Ask ONLY for what is missing (yes/no).',
          '',
          'Collect:',
          '- cyber_backups_exist',
          '- cyber_antivirus_installed',
          '- cyber_firewall_installed',
          '- cyber_backup_frequency (if backups exist)',
        ].join('\n'),
        fieldsToCollect: ['cyber_backups_exist', 'cyber_antivirus_installed', 'cyber_firewall_installed', 'cyber_backup_frequency', 'cyber_backup_frequency_other'],
        orchestration: {
          customCompletionCheck: {
            condition: 'cyber_backup_frequency !== "other"',
            requiredFields: ['cyber_backups_exist', 'cyber_antivirus_installed', 'cyber_firewall_installed', 'cyber_backup_frequency'],
          },
        },
        nextStage: 'cyberIncidents',
      },
      cyberIncidents: {
        name: 'Cyber incidents',
        description: 'Map to annex_a_cyber.cyber_incidents_last_5_years',
        prompt: [
          'You are Choco (שוקו). Keep it short.',
          'Ask:',
          '- cyber_incident_last_5_years (כן/לא)',
          'If yes, ask for one short sentence details.',
        ].join('\n'),
        fieldsToCollect: ['cyber_incident_last_5_years', 'cyber_incident_last_5_years_details'],
        nextStage: 'saveIntake',
      },
      medPiBasics: {
        name: 'Med PI proposal (basics)',
        description: 'Collect minimal data for para-medical / therapists professional liability proposal.',
        prompt: [
          'LANGUAGE: Maintain same language throughout. Hebrew → Hebrew. English → English.',
          '',
          'You are Choco (שוקו), specialized in therapists and para-medical professions.',
          'The customer is NOT an insurance expert. Keep it simple.',
          '',
          'Ask ONLY for what is missing. Prefer ONE short question.',
          '',
          'Collect:',
          '- policy_term_start_date (מתי להתחיל את הביטוח?)',
          '- med_pi_profession (תחום טיפול/מקצוע)',
          '- med_pi_years_experience (שנות ניסיון)',
          '- med_pi_licensed (יש רישיון/תעודה? כן/לא)',
          '- med_pi_works_with_children (מטפל/ת בילדים? כן/לא)',
          '- med_pi_sessions_per_week (מפגשים לשבוע בערך)',
        ].join('\n'),
        fieldsToCollect: [
          'policy_term_start_date',
          'med_pi_profession',
          'med_pi_years_experience',
          'med_pi_licensed',
          'med_pi_works_with_children',
          'med_pi_sessions_per_week',
        ],
        nextStage: 'medPiHistory',
      },
      medPiHistory: {
        name: 'Med PI history',
        description: 'Collect simple history/disclosure for professional liability.',
        prompt: [
          'You are Choco (שוקו). Ask 1-2 short questions.',
          '1) היו תביעות/אירועים מקצועיים ב־5 השנים האחרונות? (כן/לא)',
          'If yes, ask for one short sentence details.',
        ].join('\n'),
        fieldsToCollect: ['med_pi_claims_last_5_years', 'med_pi_claims_last_5_years_details'],
        nextStage: 'saveIntake',
      },
      businessAddress: {
        name: 'Business address',
        description: 'Collect insured business main location address (Israel).',
        prompt: [
          'You are Choco (שוקו).',
          'Ask ONLY for what is missing.',
          '',
          'Collect business address (כתובת העסק):',
          '- business_city',
          '- business_street',
          '- business_house_number',
          '',
          'Keep it short.',
        ].join('\n'),
        fieldsToCollect: ['business_city', 'business_street', 'business_house_number'],
        nextStage: 'buildingBasics',
      },
      buildingBasics: {
        name: 'Building basics',
        description: 'Collect a few building details needed for the proposal form (not too technical).',
        prompt: [
          'You are Choco (שוקו). Keep it simple.',
          'Ask ONLY for what is missing.',
          '',
          'Collect:',
          '- building_relationship_to_building (בעלות/שכירות)',
          '- building_area_sqm (מ״ר בערך)',
          '- building_year_built (שנת בנייה משוערת, אם יודעים)',
          '',
          'If the user does not know year built, it can be left empty.',
        ].join('\n'),
        fieldsToCollect: [
          'building_relationship_to_building',
          'building_area_sqm',
          'building_year_built',
        ],
        nextStage: 'securityBasics',
      },
      securityBasics: {
        name: 'Security basics',
        description: 'Collect simple yes/no safety/security questions.',
        prompt: [
          'You are Choco (שוקו). Keep it simple and quick.',
          'Ask ONLY for what is missing.',
          '',
          'Collect (yes/no):',
          '- has_fire_extinguishers (יש מטפים?)',
          '- has_smoke_detectors (יש גלאי עשן?)',
          '- has_alarm_system (יש אזעקה?)',
        ].join('\n'),
        fieldsToCollect: ['has_fire_extinguishers', 'has_smoke_detectors', 'has_alarm_system'],
        nextStage: 'coreCoverages',
      },
      coreCoverages: {
        name: 'Core coverages',
        description: 'Collect the key coverage amounts a small business usually needs (simple language).',
        prompt: [
          'You are Choco (שוקו). The customer is not an insurance expert.',
          'Ask ONLY for what is missing.',
          '',
          'Collect core amounts (ש״ח):',
          '- contents_sum_insured_ils (תכולה)',
          '- stock_sum_insured_ils (מלאי, אם יש)',
          '- third_party_limit_ils (צד ג׳ — גבול אחריות לאירוע)',
          '- employees_count (מספר עובדים)',
          '',
          'If the customer says "סטנדרט", choose reasonable defaults and proceed.',
        ].join('\n'),
        fieldsToCollect: [
          'contents_sum_insured_ils',
          'stock_sum_insured_ils',
          'third_party_limit_ils',
          'employees_count',
        ],
        nextStage: 'historyDisclosures',
      },
      historyDisclosures: {
        name: 'Claims history',
        description: 'Collect simple disclosure questions (yes/no).',
        prompt: [
          'You are Choco (שוקו). Ask only two short yes/no questions.',
          '',
          '1) היו תביעות ביטוח ב־5 השנים האחרונות?',
          '2) היה פריצה/ניסיון פריצה ב־5 השנים האחרונות?',
          '',
          'If the answer is yes, ask for 1 short sentence of details next.',
        ].join('\n'),
        fieldsToCollect: ['claims_last_5_years', 'burglary_or_attempt_last_5_years'],
        nextStage: 'saveIntake',
      },
      saveIntake: {
        name: 'Save intake payload',
        description: 'Create a versioned InsuranceIntake payload for this case.',
        fieldsToCollect: [],
        action: {
          toolName: 'insurance.saveIntake',
          condition: 'true',
          allowReExecutionOnError: true,
          onError: {
            behavior: 'pause',
            message: 'יש בעיה זמנית בשמירת טופס ההצעה. אפשר לנסות שוב בעוד רגע.',
          },
        },
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'This stage runs silently to save the intake JSON payload.',
        ].join('\n'),
        nextStage: 'generatePdfs',
      },
      generatePdfs: {
        name: 'Generate PDFs',
        description: 'Generate the carrier PDF proposal form(s) from the latest intake payload.',
        fieldsToCollect: [],
        action: {
          toolName: 'insurance.generatePdfs',
          condition: 'true',
          allowReExecutionOnError: true,
          onError: {
            behavior: 'pause',
            message: 'יש בעיה זמנית ביצירת ה־PDF. אפשר לנסות שוב בעוד רגע.',
          },
        },
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'This stage runs silently to generate the PDF document(s).',
        ].join('\n'),
        nextStage: 'done',
      },
      done: {
        name: 'Done',
        description: 'Proposal PDF generated. Confirm next steps.',
        fieldsToCollect: [],
        prompt: [
          'You are Choco (שוקו), an insurance broker.',
          'Confirm that the proposal PDF has been generated and we are ready to submit to the insurance carrier.',
          'Ask one short question: "Do you have any additional documents to attach (e.g., business license, previous policy)?"',
          '',
          'Hebrew example:',
          '"מעולה — יצרתי את טופס ההצעה ב־PDF ואפשר להגיש אותו לחברת הביטוח. יש לך מסמכים נוספים לצירוף (למשל רישיון עסק/פוליסה קודמת)?"',
        ].join('\n'),
        nextStage: 'done',
      },
    },
    fields: {
      questionnaire_answer: {
        type: 'string',
        description: 'Raw answer to the current dynamic questionnaire question (verbatim).',
      },
      questionnaire_complete: {
        type: 'boolean',
        description: 'Whether the dynamic questionnaire has no more relevant questions.',
      },
      questionnaire_current_qid: {
        type: 'string',
        description: 'Current questionnaire question ID (q_id).',
      },
      questionnaire_last_qid: {
        type: 'string',
        description: 'Last answered questionnaire question ID (q_id).',
      },
      questionnaire_stage_key: {
        type: 'string',
        description: 'Current questionnaire stage_key.',
      },
      questionnaire_stage_title_he: {
        type: 'string',
        description: 'Current questionnaire stage title (Hebrew).',
      },
      questionnaire_field_key: {
        type: 'string',
        description: 'Current questionnaire field_key_en.',
      },
      questionnaire_json_path: {
        type: 'string',
        description: 'Canonical JSON path to write the answer into (json_path).',
      },
      questionnaire_prompt_he: {
        type: 'string',
        description: 'Current questionnaire prompt (Hebrew).',
      },
      questionnaire_options_he: {
        type: 'string',
        description: 'Current questionnaire options (Hebrew, comma separated).',
      },
      questionnaire_constraints: {
        type: 'string',
        description: 'Current questionnaire constraints (for validation).',
      },
      questionnaire_channel: {
        type: 'string',
        description: 'Questionnaire channel profile in use (web_chat / whatsapp).',
      },
      questionnaire_stage_intro_to_send: {
        type: 'string',
        description: 'Optional stage intro sentence to send before the next question.',
      },
      insured_form_json: {
        type: 'string',
        description: 'Draft canonical proposal JSON constructed by the dynamic questionnaire (JSON string).',
      },
      attachments_checklist_pending_json: {
        type: 'string',
        description: 'Pending attachments checklist (JSON string).',
      },
      attachments_checklist_pending_count: {
        type: 'number',
        description: 'Count of pending attachments.',
      },
      handoff_required: {
        type: 'boolean',
        description: 'Whether underwriting/human handoff is required based on triggers.',
      },
      handoff_reasons_he: {
        type: 'string',
        description: 'Human-readable Hebrew reasons for handoff triggers.',
      },
      business_city: {
        type: 'string',
        description: 'Business city (address).',
      },
      business_street: {
        type: 'string',
        description: 'Business street (address).',
      },
      business_house_number: {
        type: 'string',
        description: 'Business house number (address).',
      },
      policy_term_start_date: {
        type: 'string',
        description: 'Policy start date (YYYY-MM-DD).',
      },
      policy_term_end_date: {
        type: 'string',
        description: 'Policy end date (YYYY-MM-DD) if explicitly set.',
      },
      business_legal_entity_type: {
        type: 'string',
        enum: [
          'private_company',
          'public_company',
          'registered_partnership',
          'authorized_dealer',
          'small_dealer',
          'other',
        ],
        description: 'Business legal entity type (Clal form enum).',
      },
      business_type: {
        type: 'string',
        enum: ['office', 'store', 'workshop', 'factory', 'warehouse', 'other'],
        description: 'Business premises type (Clal form enum).',
      },
      business_type_other: {
        type: 'string',
        description: 'If business_type is other, short free text.',
      },
      building_relationship_to_building: {
        type: 'string',
        enum: ['owner', 'tenant', 'long_term_lessee'],
        description: 'Relationship to the building (owner/tenant/long term lessee).',
      },
      building_area_sqm: {
        type: 'number',
        description: 'Approximate business area in square meters.',
      },
      building_year_built: {
        type: 'number',
        description: 'Approximate year built (if known).',
      },
      has_fire_extinguishers: {
        type: 'boolean',
        description: 'Whether there are fire extinguishers on site.',
      },
      has_smoke_detectors: {
        type: 'boolean',
        description: 'Whether there are smoke detectors on site.',
      },
      has_alarm_system: {
        type: 'boolean',
        description: 'Whether there is an alarm system on site.',
      },
      cyber_limit_per_claim_and_period_ils: {
        type: 'number',
        description: 'Cyber limit per claim and period (ILS).',
      },
      employees_count: {
        type: 'number',
        description: 'Number of employees.',
      },
      contents_sum_insured_ils: {
        type: 'number',
        description: 'Contents sum insured in ILS.',
      },
      stock_sum_insured_ils: {
        type: 'number',
        description: 'Stock sum insured in ILS (if applicable).',
      },
      third_party_limit_ils: {
        type: 'number',
        description: 'Third party liability limit per event in ILS.',
      },
      claims_last_5_years: {
        type: 'boolean',
        description: 'Whether there were claims in the last 5 years.',
      },
      burglary_or_attempt_last_5_years: {
        type: 'boolean',
        description: 'Whether there was burglary/attempt in the last 5 years.',
      },
      // Cyber extras (re-used from needsDiscovery, available here too)
      cyber_backups_exist: { type: 'boolean', description: 'Cyber: backups exist.' },
      cyber_backup_frequency: {
        type: 'string',
        enum: ['daily', 'every_2_days', 'weekly', 'biweekly', 'other'],
        description: 'Cyber: backup frequency enum.',
      },
      cyber_backup_frequency_other: { type: 'string', description: 'Cyber: backup frequency other.' },
      cyber_antivirus_installed: { type: 'boolean', description: 'Cyber: antivirus installed.' },
      cyber_firewall_installed: { type: 'boolean', description: 'Cyber: firewall installed.' },
      cyber_incident_last_5_years: { type: 'boolean', description: 'Cyber: incident last 5 years.' },
      cyber_incident_last_5_years_details: { type: 'string', description: 'Cyber: incident details.' },
      // Med PI extras
      med_pi_profession: { type: 'string', description: 'Med PI: profession.' },
      med_pi_years_experience: { type: 'number', description: 'Med PI: years experience.' },
      med_pi_licensed: { type: 'boolean', description: 'Med PI: licensed/certified.' },
      med_pi_works_with_children: { type: 'boolean', description: 'Med PI: works with children.' },
      med_pi_sessions_per_week: { type: 'number', description: 'Med PI: sessions per week.' },
      med_pi_claims_last_5_years: { type: 'boolean', description: 'Med PI: claims last 5 years.' },
      med_pi_claims_last_5_years_details: { type: 'string', description: 'Med PI: claims details.' },
    },
    config: {
      initialStage: 'routeByProduct',
    },
  },
};

