import { FlowSchema } from '../types';

export const campaignManagementFlowSchema: FlowSchema = {
  name: 'ChocoAI Campaign Management Flow',
  slug: 'campaignManagement',
  description: 'Campaign management flow for users with configured account',
  version: 12,
  definition: {
    config: {
      initialStage: 'bootstrap',
    },
    stages: {
      bootstrap: {
        name: 'Bootstrap Workspace',
        description: 'Refresh org context (entities + gateways) before campaign work',
        fieldsToCollect: [],
        prompt: [
          'You are a senior fundraising campaign specialist and campaign operations manager.',
          'We are about to help the user plan/manage a campaign — but first quietly refresh workspace context (entities + gateways).',
          'Do NOT ask the user anything here. No user-facing message.',
        ].join('\n'),
        action: {
          toolName: 'login.checkAccountContext',
          allowReExecutionOnError: true,
          onErrorCode: {
            JWT_MISSING: { behavior: 'pause' },
            JWT_INVALID: { behavior: 'pause' },
          },
          onError: {
            behavior: 'continue',
            message: 'יש תקלה זמנית בטעינת נתוני החשבון. נסה שוב בעוד רגע.',
          },
        },
        nextStage: 'loadCampaignsOnEntry',
      },
      loadCampaignsOnEntry: {
        name: 'Load Campaigns On Entry',
        description: 'Immediately load campaigns so we can route correctly (create vs manage vs content improvements).',
        fieldsToCollect: [],
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'Quietly load campaigns for the selected org so we can route the user correctly.',
        ].join('\n'),
        action: {
          toolName: 'flow.loadCampaignsContext',
          allowReExecutionOnError: true,
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          // @ts-ignore - flow schema typing does not model arbitrary tool payload keys
          force_live: true,
          onErrorCode: {
            JWT_MISSING: { behavior: 'pause' },
            JWT_INVALID: { behavior: 'pause' },
          },
          onError: {
            behavior: 'continue',
            message: 'יש תקלה זמנית בטעינת הקמפיינים. נמשיך בינתיים ואחזור לזה בהמשך.',
          },
        },
        nextStage: 'campaignEntryRouter',
      },
      campaignEntryRouter: {
        name: 'Campaign Entry Router',
        description: 'Route based on whether there are campaigns and whether one is upcoming.',
        fieldsToCollect: [],
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'This stage only routes the user to the right campaign experience.',
        ].join('\n'),
        nextStage: {
          conditional: [
            // If there are no campaigns at all, immediately start a creation strategist conversation.
            { condition: 'has_campaigns === false || has_campaigns === "false" || campaigns_count === 0', ifTrue: 'campaignStrategyCreate' },

            // If there is exactly one upcoming (scheduled) campaign, offer content improvements before launch.
            {
              condition:
                '(campaigns_count === 1 || campaigns_count === "1") && (has_upcoming_campaign === true || has_upcoming_campaign === "true") && !!upcoming_campaign_id',
              ifTrue: 'upcomingCampaignContentFetch',
            },

            // If there are multiple campaigns, ask which one to work on.
            { condition: 'campaigns_count > 1 || campaigns_count === "2" || campaigns_count === "3"', ifTrue: 'chooseCreateOrManageCampaign' },
          ],
          fallback: 'campaignWelcome',
        },
      },
      upcomingCampaignContentFetch: {
        name: 'Upcoming Campaign Content Fetch',
        description: 'Fetch campaign + story content so we can propose improvements before launch.',
        fieldsToCollect: [],
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'Fetch the upcoming campaign content and prepare a helpful, human review.',
        ].join('\n'),
        action: {
          toolName: 'choco.getCampaignWithContent',
          condition: '!!upcoming_campaign_id',
          allowReExecutionOnError: true,
          onError: {
            behavior: 'continue',
            message: 'לא הצלחתי למשוך את תוכן דף הקמפיין כרגע. נמשיך ונבנה יחד תוכן חזק, ואנסה שוב עוד רגע.',
          },
        },
        nextStage: 'upcomingCampaignContentReview',
      },
      upcomingCampaignContentReview: {
        name: 'Upcoming Campaign Content Review',
        description: 'Offer improvements to the campaign story content for a scheduled campaign.',
        fieldsToCollect: ['cm_user_intent'],
        prompt: [
          'You are a senior fundraising campaign specialist.',
          'The user already has a campaign scheduled (not started yet).',
          '',
          'First, say ONE short, motivating sentence that frames this as “let’s sharpen the story before launch”.',
          'Then do a quick review:',
          '- Summarize the current story in 1–2 lines (no criticism yet).',
          '- Offer 3–5 concrete improvement ideas (headline, opening hook, urgency, credibility, donation impact, CTA).',
          '',
          'Context (may be empty):',
          '- Campaign title: {campaign_title}',
          '- Upcoming start date (unix): {upcoming_campaign_start_date}',
          '- Existing story (html or text): {campaign_story_html}',
          '',
          'Ask ONE question to move forward:',
          '- “רוצה שאנסח לך גרסה משופרת לטקסט (ואז נעלה אותה לדף), או שנלטש יחד לפי נקודות שאתה נותן לי?”',
          '',
          'Set cm_user_intent="manage_campaign".',
        ].join('\n'),
        nextStage: 'selectCampaignAction',
      },
      campaignWelcome: {
        name: 'Campaign Welcome',
        description: 'One-line announcement that we are ready to start campaign work',
        fieldsToCollect: [],
        prompt: [
          'You are a senior fundraising campaign specialist.',
          '',
          'Send ONE short opening sentence that announces we are ready to start the campaign now.',
          'Then ask ONE engaging question to kick off the campaign work (not technical, not a menu).',
          '',
          'Examples:',
          '- Hebrew: "מעולה — הכול מוכן, בוא נרים קמפיין חזק. מה המטרה המרכזית שלך בקמפיין הזה?"',
          '- English: "Great — everything’s ready. Let’s build a strong campaign. What’s the main goal you want to hit?"',
          '',
          'CRITICAL: This message must NOT block anything. After this, the normal dashboard flow continues.',
        ].join('\n'),
        nextStage: 'dashboard',
      },
      dashboard: {
        name: 'Dashboard',
        description: 'Main dashboard for campaign management',
        fieldsToCollect: ['cm_user_intent'],
        prompt: [
          'IMPORTANT: You are in **dashboard management mode**, NOT registration/onboarding.',
          'Do NOT say anything about "registration", "sign up", or "continue to registration".',
          'The user is already logged in and we are managing their workspace.',
          '',
          'You are a senior fundraising campaign specialist.',
          'Your goal is to help the user launch and manage campaigns like a pro (strategy + execution).',
          'Please identify the user\'s intent from their latest message and classify it into one of the following categories:',
          '- "manage_entity": User wants to Create, Update, or Delete a Legal Entity.',
          '- "manage_campaign": User wants to Create, Update, or Delete a Campaign.',
          '- "setup_gateway": User wants to add or setup a payment gateway (Meshulam, Stripe).',
          '- "general_inquiry": User has a question or request not covered above.',
          '',
          'If the intent is clear, set the "cm_user_intent" field accordingly.',
          'If the user just says "hi" or general pleasantries, reply warmly as a campaign specialist and ask what they want to achieve with their campaign right now.',
          'Current capabilities: Managing entities, Managing campaigns, Setting up payment gateways.',
          '',
          'IMPORTANT:',
          '- If any action requires Choco Protected APIs, user must be logged in (jwt_token present).',
          '- If a tool returns errorCode "JWT_MISSING", tell the user they need to log in and ask them to log in now.',
          '',
          'TONE:',
          '- Sound like an experienced campaign specialist (help them hit goals, get the campaign live).',
          '- Avoid technical jargon unless the user asks.',
          '- Respond in the user’s language (Hebrew ↔ Hebrew, English ↔ English).',
          '',
          'PRIORITY:',
          '- Keep the conversation focused on campaign strategy and launching the campaign.',
          '- Only talk about gateways/entities if there is a real blocker (missing required setup).',
          '',
          'DEFAULT BEHAVIOR:',
          '- If the user did not clearly ask for entity/gateway work, assume they want to work on their campaign.',
        ].join('\n'),
        action: {
          // Deterministic guardrail: fix obvious misclassification cases (e.g. "אני רוצה להקים קמפיין")
          toolName: 'flow.detectCampaignManagementIntent',
          condition: 'true',
          allowReExecutionOnError: true,
        },
        nextStage: {
          conditional: [
            {
              condition: 'cm_user_intent == "manage_entity"',
              ifTrue: 'selectEntityAction',
            },
            {
              condition: 'cm_user_intent == "manage_campaign"',
              ifTrue: 'selectCampaignAction',
            },
            {
              condition: 'cm_user_intent == "setup_gateway"',
              ifTrue: 'collectGatewayDetails',
            },
            {
              condition: 'cm_user_intent == "general_inquiry"',
              // Don't show a generic menu; default into campaign work.
              ifTrue: 'selectCampaignAction',
            },
          ],
          fallback: 'selectCampaignAction',
        },
      },
      selectCampaignAction: {
        name: 'Select Campaign Action',
        description: 'Load existing campaigns and decide whether to create or manage one',
        fieldsToCollect: [],
        prompt: [
          'You are a campaign strategist.',
          'First, quietly check if there are existing campaigns in this workspace.',
          'If there are none, assume they want to create a new campaign and move into an exciting “new campaign” conversation.',
        ].join('\n'),
        action: {
          toolName: 'flow.loadCampaignsContext',
          allowReExecutionOnError: true,
          onErrorCode: {
            JWT_MISSING: { behavior: 'pause' },
            JWT_INVALID: { behavior: 'pause' },
          },
        },
        nextStage: {
          conditional: [
            // If we have no campaigns, default to create (tool sets campaign_action='create')
            { condition: 'has_campaigns === false || has_campaigns === "false"', ifTrue: 'campaignStrategyCreate' },
            { condition: 'has_campaigns === true || has_campaigns === "true"', ifTrue: 'chooseCreateOrManageCampaign' },
          ],
          fallback: 'selectCampaignAction',
        },
      },
      chooseCreateOrManageCampaign: {
        name: 'Choose Create or Manage',
        description: 'Offer create vs manage existing campaigns (do not suggest delete unless user explicitly asks)',
        fieldsToCollect: ['campaign_action', 'campaign_choice'],
        prompt: [
          'You are a senior fundraising campaign specialist.',
          '',
          'We found existing campaigns in this workspace:',
          '{campaigns_list}',
          '',
          'Ask ONE question in a warm, confident tone (not a menu):',
          '- Do you want to launch a brand‑new campaign now, or work on one of the existing campaigns?',
          '',
          'If they want to manage an existing one, ask them to pick by the NUMBER from the list or by the campaign name.',
          '',
          'RULES:',
          '- If they want a new one: set campaign_action="create".',
          '- If they want to manage an existing one: set campaign_action="update" and collect campaign_choice (number or name).',
          '- Only set campaign_action="delete" if the user explicitly asks to delete/cancel/remove a campaign.',
          '',
          'Keep it friendly, motivating, non-technical.',
        ].join('\n'),
        nextStage: {
          conditional: [
            { condition: 'campaign_action == "create"', ifTrue: 'campaignStrategyCreate' },
            { condition: 'campaign_action == "update" && !!campaign_choice', ifTrue: 'campaignStrategyManage' },
            { condition: 'campaign_action == "delete" && !!campaign_id', ifTrue: 'executeManageCampaign' },
          ],
          fallback: 'chooseCreateOrManageCampaign',
        },
      },
      campaignStrategyCreate: {
        name: 'Campaign Strategy (Create)',
        description: 'Campaign strategist conversation for creating a new campaign',
        fieldsToCollect: [
          'campaign_action',
          'campaign_title',
          'campaign_start_date',
          'campaign_end_date',
          'campaign_primary_goal',
          'campaign_currency',
          'campaign_bonus_goal',
        ],
        prompt: [
          'You are a senior fundraising campaign specialist.',
          'We are creating a NEW campaign.',
          '',
          'Tone: warm, energetic, confident. Make the customer excited and feel guided.',
          'Style: NOT a form. You are allowed (and encouraged) to share your thoughts, suggestions, and a mini-plan.',
          '',
          'If campaign_brief exists (from earlier in the conversation), start by referencing it and building momentum from it (do NOT re-ask what the campaign is about).',
          '',
          'CRITICAL UX RULES:',
          '- Do NOT ask for campaign_id. Do NOT mention IDs at all (internal only).',
          '- Do NOT ask for “all details in one message”.',
          '- Ask ONE question at a time — but you can add 1–2 helpful sentences of advice before the question.',
          '- Start by reflecting what they want to do, then propose direction.',
          '',
          'Conversation arc (repeat as needed):',
          '1) Mirror & excite: 1–2 sentences that summarize their cause in a motivating way.',
          '2) Share your thoughts: give 2–3 concrete campaign ideas (story angle, audiences, channels, timeline).',
          '3) Propose a simple plan: “We’ll set goal + dates + title, then we’ll tune messaging”.',
          '4) Ask ONE question that moves the campaign forward.',
          '',
          'Behind-the-scenes data you must eventually collect (only when needed, naturally):',
          '- campaign_currency (ILS/USD) [required for create]',
          '- campaign_start_date (unix timestamp) [required for create]',
          '- campaign_primary_goal (number) [required for create]',
          '- campaign_title (recommended)',
          '- campaign_end_date (optional)',
          '- campaign_bonus_goal (optional)',
          '',
          'Hints:',
          '- If they speak Hebrew / Israel context, you can assume ILS and just ask for confirmation later.',
          '- If they don’t know dates yet, propose a default window (e.g., 10–21 days) and ask if it fits.',
          '- If they don’t know the goal yet, propose a starting range and ask what feels realistic.',
          '',
          'Never re-ask anything they already provided.',
        ].join('\n'),
        nextStage: 'executeManageCampaign',
      },
      campaignStrategyManage: {
        name: 'Campaign Strategy (Manage)',
        description: 'Campaign strategist conversation for updating an existing campaign',
        fieldsToCollect: [
          'campaign_action',
          'campaign_choice',
          'campaign_id',
          'campaign_title',
          'campaign_start_date',
          'campaign_end_date',
          'campaign_primary_goal',
          'campaign_currency',
          'campaign_bonus_goal',
        ],
        prompt: [
          'You are a senior fundraising campaign specialist.',
          'We are managing an EXISTING campaign.',
          '',
          'CRITICAL UX RULES:',
          '- The user should select by number/name (campaign_choice). Never ask for campaign_id and never show IDs.',
          '- Ask ONE question at a time. Do NOT ask for everything in one message.',
          '',
          'First: confirm which campaign they mean (by number/name), then ask what they want to improve/change (goal? dates? title? content strategy?).',
        ].join('\n'),
        action: {
          toolName: 'flow.resolveCampaignSelection',
          condition: 'campaign_action == "update" && (!campaign_id || campaign_id == "") && !!campaign_choice',
          allowReExecutionOnError: true,
          onError: {
            behavior: 'continue',
            message: 'לא הצלחתי לזהות איזה קמפיין לבחור. אפשר לבחור לפי המספר מהרשימה או לרשום את שם הקמפיין בדיוק?',
          },
        },
        nextStage: 'executeManageCampaign',
      },
      executeManageCampaign: {
        name: 'Execute Campaign Action',
        description: 'Runs campaign create/update/delete via ChocoAPI',
        fieldsToCollect: [],
        prompt: 'Great — I’m on it. One moment while I update things on your dashboard…',
        action: {
          toolName: 'choco.add-campaign',
          onErrorCode: {
            JWT_MISSING: {
              behavior: 'pause',
            },
          },
          onError: {
            behavior: 'continue',
            message: 'Failed to manage campaign. Please try again.',
          },
        },
        nextStage: 'resetIntent',
      },

      selectEntityAction: {
        name: 'Select Entity Action',
        description: 'Determine whether the user wants to create, update, or delete a legal entity',
        fieldsToCollect: ['entity_action'],
        prompt: [
          'You are a campaign specialist.',
          'If the user wants to work on “legal entities”, keep it practical and non-technical: explain it as “who receives the funds / payout details”.',
          'Ask what they want to do: create a new payout entity, update details, or remove one (only if they explicitly asked).',
          '',
          'Set "entity_action" to one of: create, update, delete.',
          'If update/delete, ask them to pick by name/number (never ask for internal IDs).',
        ].join('\n'),
        nextStage: {
          conditional: [
            { condition: 'entity_action == "create"', ifTrue: 'collectEntityDetails' },
            { condition: 'entity_action == "update"', ifTrue: 'collectEntityDetails' },
            { condition: 'entity_action == "delete"', ifTrue: 'collectEntityDeleteDetails' },
          ],
          fallback: 'selectEntityAction',
        },
      },
      collectEntityDeleteDetails: {
        name: 'Collect Entity ID',
        description: 'Collect the entity id for deletion',
        fieldsToCollect: ['entity_id'],
        prompt: [
          'You are a campaign specialist.',
          'Do NOT ask for internal IDs.',
          'Ask them which payout entity to remove by name (or number from the list you showed earlier).',
        ].join('\n'),
        nextStage: 'executeManageEntity',
      },
      collectEntityDetails: {
        name: 'Collect Entity Details',
        description: 'Collect entity details (create/update)',
        fieldsToCollect: [
          'entity_id',
          'entity_name',
          'entity_tax_id',
          'entity_country',
          'entity_address_line_1',
          'entity_address_line_2',
          'entity_city',
          'entity_state',
          'entity_zip',
        ],
        prompt: [
          'You are a campaign specialist.',
          'Collect the payout entity details needed for this action — keep it human and minimal.',
          '',
          'For create: name, tax_id, country, address_line_1, city, zip are required.',
          'For update: entity_id is required; only collect fields the user wants to change.',
        ].join('\n'),
        nextStage: 'executeManageEntity',
      },
      executeManageEntity: {
        name: 'Execute Entity Action',
        description: 'Runs entity create/update/delete via ChocoAPI',
        fieldsToCollect: [],
        prompt: 'Executing entity action...',
        action: {
          toolName: 'choco.add-entity',
          onErrorCode: {
            JWT_MISSING: {
              behavior: 'pause',
            },
          },
          onError: {
            behavior: 'continue',
            message: 'Failed to manage entity. Please try again or check details.',
          },
        },
        nextStage: 'resetIntent',
      },

      collectGatewayDetails: {
        name: 'Collect Gateway Details',
        description: 'Collect payment gateway provider and required credentials',
        fieldsToCollect: ['gateway_provider', 'gateway_api_key', 'gateway_user_id', 'gateway_org_custom_id'],
        prompt: [
          'You are a campaign specialist.',
          'Only go into payment/gateway details if it’s a real blocker to launching/receiving donations.',
          'Explain it simply as “how donors can pay”.',
          '',
          'Set "gateway_provider" to one of: grow/meshulam/stripe.',
          'If meshulam/grow: you may need gateway_user_id and gateway_api_key depending on the stage.',
          'If stripe: follow the Stripe flow requirements.',
        ].join('\n'),
        nextStage: 'executeSetupGateway',
      },
      executeSetupGateway: {
        name: 'Execute Gateway Setup',
        description: 'Executes the addPaymentGateway tool',
        fieldsToCollect: [],
        prompt: 'מעולה — אני מסדר את זה עכשיו כדי שתוכלו לקבל תרומות. רגע אחד…',
        action: {
          toolName: 'choco.add-payment-gateway',
          onErrorCode: {
            JWT_MISSING: {
              behavior: 'pause',
            },
          },
          onError: {
            behavior: 'continue',
            message: 'There was an error setting up the payment gateway.',
          },
        },
        nextStage: 'resetIntent',
      },
      resetIntent: {
        name: 'Reset Intent',
        description: 'Clears the intent field to allow re-selection',
        fieldsToCollect: [],
        prompt: 'מעולה — מה תרצה לעשות עכשיו כדי לקדם את הקמפיין?',
        action: {
          toolName: 'flow.reset-campaign-intent',
          onError: { behavior: 'continue' },
        },
        nextStage: 'dashboard',
      },
    },
    fields: {
      cm_user_intent: {
        type: 'string',
        description: 'The user intent for campaign management actions',
        enum: ['manage_entity', 'manage_campaign', 'setup_gateway', 'general_inquiry'],
      },
      campaign_action: {
        type: 'string',
        description: 'Campaign action to perform',
        enum: ['create', 'update', 'delete'],
      },
      campaign_id: { type: 'string', description: 'Campaign ID' },
      campaign_choice: { type: 'string', description: 'User-facing campaign choice (number or name); resolved to campaign_id internally' },
      campaigns_list: { type: 'string', description: 'Formatted list of existing campaigns for display' },
      campaigns_json: { type: 'string', description: 'Campaigns JSON (internal)' },
      has_campaigns: { type: 'boolean', description: 'Whether the workspace has any campaigns' },
      has_active_campaigns: { type: 'boolean', description: 'Whether the workspace has active campaigns' },
      campaigns_count: { type: 'number', description: 'How many campaigns exist for the selected organization' },
      campaigns_source: { type: 'string', description: 'Where campaigns came from (cache|live)' },
      has_upcoming_campaign: { type: 'boolean', description: 'Whether there is a scheduled campaign (start_date in the future)' },
      upcoming_campaign_id: { type: 'string', description: 'Upcoming campaign id (internal)' },
      upcoming_campaign_title: { type: 'string', description: 'Upcoming campaign title (user-facing)' },
      upcoming_campaign_start_date: { type: 'number', description: 'Upcoming campaign start date (unix seconds)' },
      campaign_story_html: { type: 'string', description: 'Primary campaign story content (html) for review' },
      campaign_title: { type: 'string', description: 'Campaign title' },
      campaign_start_date: { type: 'number', description: 'Campaign start date (Unix timestamp)' },
      campaign_end_date: { type: 'number', description: 'Campaign end date (Unix timestamp)' },
      campaign_primary_goal: { type: 'number', description: 'Campaign primary goal' },
      campaign_currency: { type: 'string', description: 'Campaign currency (ILS/USD)' },
      campaign_bonus_goal: { type: 'number', description: 'Campaign bonus goal' },
      campaign_brief: { type: 'string', description: 'Freeform campaign brief collected earlier (optional)' },

      entity_action: {
        type: 'string',
        description: 'Entity action to perform',
        enum: ['create', 'update', 'delete'],
      },
      entity_id: { type: 'string', description: 'Entity ID' },
      entity_name: { type: 'string', description: 'Entity legal name' },
      entity_tax_id: { type: 'string', description: 'Entity tax id / registration number' },
      entity_country: { type: 'string', description: 'Entity country ISO code' },
      entity_address_line_1: { type: 'string', description: 'Entity address line 1' },
      entity_address_line_2: { type: 'string', description: 'Entity address line 2' },
      entity_city: { type: 'string', description: 'Entity city' },
      entity_state: { type: 'string', description: 'Entity state/province' },
      entity_zip: { type: 'string', description: 'Entity zip/postal' },

      gateway_provider: { type: 'string', description: 'Gateway provider (grow/meshulam/stripe)' },
      gateway_api_key: { type: 'string', description: 'Gateway api key' },
      gateway_user_id: { type: 'string', description: 'Gateway user id' },
      gateway_org_custom_id: { type: 'string', description: 'Gateway org custom id' },
    },
  },
};
