import { FlowSchema } from '../types';

export const needsDiscoveryFlowSchema: FlowSchema = {
  name: 'ChocoAI Needs Discovery Flow',
  slug: 'needsDiscovery',
  description: 'Insurance intake: identify the insured business and clarify coverage needs',
  version: 1,
  definition: {
    stages: {
      identifyCustomer: {
        name: 'Identify customer',
        description: 'Identify the insured business and primary contact person.',
        prompt: [
          'LANGUAGE: Maintain same language throughout. Hebrew → Hebrew. English → English.',
          '',
          'You are Shoko (שוקו), an insurance broker.',
          'Goal: identify the business and the contact person so we can start a quote.',
          '',
          'Be simple and clear.',
          'Prefer ONE short question.',
          'Use a numbered list (1., 2., 3., ...) ONLY when you ask for multiple items from different categories, or when the question would otherwise be long.',
          'Do NOT re-ask phone/email if already collected earlier in the conversation.',
          '',
          'Collect (only what is missing):',
          '- business_name (שם בית העסק)',
          '- legal_id_type (ח"פ / ע"מ / ת"ז)',
          '- legal_id (מספר)',
          '- first_name + last_name (איש/אשת קשר)',
          '- phone and/or email (טלפון ואימייל)',
          '',
          'If the user provides multiple details at once, accept all of them and move forward.',
        ].join('\n'),
        fieldsToCollect: [
          'business_name',
          'legal_id_type',
          'legal_id',
          'first_name',
          'last_name',
          'phone',
          'email',
        ],
        nextStage: 'needsAssessment',
      },
      needsAssessment: {
        name: 'Needs assessment',
        description: 'Clarify product line and coverage modules requested.',
        prompt: [
          'You are Shoko (שוקו), an insurance broker.',
          'Goal: understand what insurance the customer wants to buy.',
          '',
          'Keep it simple. Ask short questions.',
          'Prefer ONE short question.',
          'Use a numbered list (1., 2., 3., ...) ONLY when you ask for multiple items from different categories, or when the question would otherwise be long.',
          '',
          'Also collect core underwriting basics for SMB quotes (one question at a time, only what is missing):',
          '- industry / business_type (סוג העסק / תחום)',
          '- activity_description (תיאור פעילות)',
          '- annual_turnover_ils (מחזור שנתי משוער)',
          '- employees_count (מספר עובדים)',
          '',
          'Collect (briefly):',
          '- product_line (business_package / cyber / med_pi)',
          '- coverages_needed (free text; include: structure/contents/third-party/employers liability/special risks)',
          '- special_risks (free text; examples: professional liability, para-medical, product liability, cyber annex)',
          '',
          'Ask ONE question at a time, only for what is missing.',
        ].join('\n'),
        fieldsToCollect: [
          'product_line',
          'coverages_needed',
          'special_risks',
          'industry',
          'activity_description',
          'annual_turnover_ils',
          'employees_count',
        ],
        nextStage: 'ensureCase',
      },
      ensureCase: {
        name: 'Create insurance case',
        description: 'Create or attach an InsuranceCase for this conversation.',
        fieldsToCollect: [],
        action: {
          toolName: 'insurance.ensureCase',
          condition: 'true',
          allowReExecutionOnError: true,
          onError: {
            behavior: 'pause',
            message: 'יש תקלה זמנית בפתיחת תיק הביטוח. אפשר לנסות שוב בעוד רגע.',
          },
        },
        prompt: [
          'CRITICAL: This stage should NOT generate a response message.',
          'Do NOT generate any message.',
          'This stage runs silently to create/link an InsuranceCase.',
        ].join('\n'),
        // No nextStage → onComplete will transition to proposalForm
      },
    },
    fields: {
      business_name: {
        type: 'string',
        description: 'Insured business name (שם בית העסק).',
        minLength: 1,
      },
      legal_id_type: {
        type: 'string',
        enum: ['HP', 'AM', 'TZ', 'EIN'],
        description: 'Legal ID type: HP (ח"פ) / AM (ע"מ) / TZ (ת"ז) / EIN.',
      },
      legal_id: {
        type: 'string',
        description: 'Legal/business identifier number (digits as provided).',
        minLength: 4,
      },
      first_name: {
        type: 'string',
        description: 'Contact person first name.',
        minLength: 1,
      },
      last_name: {
        type: 'string',
        description: 'Contact person last name.',
        minLength: 1,
      },
      phone: {
        type: 'string',
        description: 'Contact mobile number (Israeli mobile preferred).',
      },
      email: {
        type: 'string',
        description: 'Contact email address.',
      },
      product_line: {
        type: 'string',
        enum: ['business_package', 'cyber', 'med_pi'],
        description: 'Requested product line (high level).',
      },
      coverages_needed: {
        type: 'string',
        description: 'Coverage modules requested (free text).',
      },
      special_risks: {
        type: 'string',
        description: 'Special risks / special clauses requested (free text).',
      },
      industry: {
        type: 'string',
        description: 'Business industry / type (SMB).',
      },
      activity_description: {
        type: 'string',
        description: 'Short description of business activity.',
      },
      annual_turnover_ils: {
        type: 'number',
        description: 'Estimated annual turnover in ILS.',
      },
      employees_count: {
        type: 'number',
        description: 'Number of employees.',
      },
    },
    config: {
      initialStage: 'identifyCustomer',
      onComplete: {
        startFlowSlug: 'proposalForm',
        mode: 'seamless',
        preserveFields: [
          'business_name',
          'legal_id_type',
          'legal_id',
          'first_name',
          'last_name',
          'phone',
          'email',
          'product_line',
          'coverages_needed',
          'special_risks',
          'industry',
          'activity_description',
          'annual_turnover_ils',
          'employees_count',
          'already_registered',
        ],
      },
    },
  },
};

