export const he = {
  Common: {
    loading: 'טוען...',
    search: 'חפש',
    tryAgain: 'נסה שוב',
    edit: 'ערוך',
    delete: 'מחק',
    ok: 'אוקיי',
    cancel: 'ביטול',
    confirm: 'יאללה',
    save: 'שמור',
    create: 'צור',
    refresh: 'רענן',
    confirmAction: 'בטוח?',
    confirmDeletionMsg: 'באמת למחוק? אין דרך חזרה',
  },

  MainLayout: {
    conversations: 'צ׳אטים',
    settings: 'הגדרות',
    systemTheme: 'כמו המערכת',
    lightTheme: 'בהיר',
    darkTheme: 'חושך',
    about: 'מי אנחנו',
    version: 'גרסה {version}',
    logout: 'צא',
  },

  LoginPage: {
    signIn: 'כניסה',
    authorizedAccessRequired: 'צריך הרשאה כפרה',
    username: 'יוזר',
    password: 'סיסמה',
    signInBtn: 'יאללה נכנס',
    signInBtnLoading: 'נכנס...',
    needHelpMsg: 'נתקעת? תקרא את ה<link>README</link> או תצעק למנהל',
    fillUsernameAndPassword: 'תמלא יוזר וסיסמה אחי',
    loginFailed: 'לא נכנס, משהו השתבש',
  },

  ConversationsPage: {
    conversations: 'צ׳אטים',
    new: 'חדש',
    failedToLoadConversations: 'הצ׳אטים לא נטענו',
    noConversationsYet: 'עדיין אין צ׳אטים',
    noMessagesYet: 'ריק פה כרגע',
    selectConversation: 'תבחר צ׳אט',
    failedToFetchConversation: 'לא הצלחתי למשוך את הצ׳אט',
    typeAMessage: 'תקליד משהו...',
    failedToCreateConversation: 'לא הצלחתי לפתוח צ׳אט חדש',
    conversationDetails: 'פרטי הצ׳אט',
    flow: 'פלואו',
    userData: 'נתונים של המשתמש',
    log: 'לוג',
    request: 'בקשה',
    response: 'תגובה',
    collected: 'נאסף',
    organisations: 'ארגונים',
  },

  SettingsPage: {
    settings: 'הגדרות',
    dashboard: 'דשבורד',
    aiProvider: 'ספק AI',
    flows: 'פלואוים',
    segments: 'סגמנטים',
    whatsapp: 'וואטסאפ',
    email: 'מייל',
    webWidget: 'וידג׳ט לאתר',
    system: 'מערכת',
    sectionWasNotFound: 'הקטע הזה נעלם',

    // AI Provider
    model: 'מודל',

    // Flows
    newFlow: 'פלואו חדש',
    failedToLoadFlows: 'הפלואוים לא נטענו',
    createFlow: 'ליצור פלואו',
    export: 'ייצוא',
    name: 'שם',
    slug: 'קוד',
    description: 'תיאור',
    failedToCreateFlow: 'לא הצלחתי ליצור את הפלואו',
    failedToDeleteFlow: 'לא הצלחתי למחוק',

    // System
    healthStatus: 'סטטוס',
    checkedAt: 'נבדק ב-{lastCheckedAt}',
  },

  FlowEditor: {
    backToList: 'חזרה לרשימה',
    name: 'שם הפלואו',
    slug: 'קוד',
    description: 'מה זה עושה',
    general: 'כללי',
    canvas: 'קנבס',
    fields: 'שדות',
    schemaJSON: 'JSON סכמה',
    validationWithCount: 'ולידציה ({errorCount})',
    defileFlowLevelFieldsMsg: 'תגדיר שדות ברמת הפלואו שישמשו בשלבים',
    noFieldsYetMsg: 'אין שדות עדיין – תוסיף אחד',
    addField: '+ שדה',
    searchFields: 'חיפוש לפי שדה/תיאור',
    sortByPriority: 'מיון לפי עדיפות (הדלקה/כיבוי)',
    type: 'סוג',
    string: 'טקסט',
    enum: 'רשימה',
    number: 'מספר',
    boolean: 'כן/לא',
    allowedValues: 'ערכים אפשריים (מופרדים בפסיקים)',
    sensitive: 'סודי',
    palette: 'פלטה',
    addStage: '+ שלב',
    setInitial: 'הפוך לראשון',
    stage: 'שלב',
    selectStageToSeeDetails: 'תבחר שלב לראות פרטים',
    action: 'אקשן',
    when: 'מתי',
    fieldsToCollect: 'מה לאסוף',
    transition: 'מעבר',
    fallback: 'ברירת מחדל',
    if: 'אם',
    true: 'כן',
    false: 'לא',
    stageSettings: 'הגדרות השלב',
    prompt: 'פרומפט',
    basics: 'בסיסי',
    noFieldsDefinedYet: 'עדיין אין שדות בתהליך',
    toolToExecute: 'כלי להריץ',
    condition: 'תנאי',
    nextStage: 'השלב הבא',
    transitionType: 'סוג מעבר',
    fixed: 'קבוע',
    conditional: 'מותנה',
    addCondition: '+ תנאי',
    ifTrue: 'אם כן',
    ifFalse: 'אם לא',
    patternRegex: 'תבנית regex',
    minLength: 'מינימום תווים',
    maxLength: 'מקסימום תווים',
    priority: 'עדיפות',
    serverValidation: 'ולידציה בשרת:',
    serverValidationEnforcedEvenIfEmpty: 'נאכפת גם אם ה־pattern ריק',
    recommendedPattern: 'תבנית מומלצת:',
    recommendedMinMax: 'מינ {min}, מקס {max}',
    applyRecommended: 'החל מומלץ',
    validationEmail: 'אימייל',
    validationIsraeliMobile: 'נייד ישראלי (מנרמל +972/רווחים/מקפים)',
    validationIsraeliId: 'ת״ז ישראלי (כולל checksum)',
    validationIlBusinessId: 'ח״פ/ע״מ (כולל checksum)',
    validation: 'ולידציה',
    noIssues: 'הכל תקין ✅',
    focus: 'פוקוס',
    initialStageIsNotSet: 'לא הגדרת שלב פתיחה',
    initialStageNotExist: 'שלב הפתיחה מצביע על משהו שלא קיים',
    edgePointsToMissingStage: 'חיבור מצביע לשלב חסר: {stage}',
    unreachableStage: 'שלב שלא ניתן להגיע אליו: {stage}',

    // Missing field references repair
    missingFieldRefsMsg: 'השלב הזה מצביע על שדות שלא קיימים בהגדרת השדות של הפלואו. אפשר להסיר אותם, או ליצור להם הגדרה כדי שנוכל לשמור.',
    createFieldDefinition: 'צור',
    removeFieldRef: 'הסר',
    createdFieldDefinition: 'נוצרה הגדרה לשדה: {slug}',
    autoCreatedMissingFieldsForSave: 'יצרתי אוטומטית {count} שדות חסרים כדי שאפשר יהיה לשמור.',
  },

  Notification: {
    info: 'אינפו',
    success: 'הצלחה 🎉',
    warning: 'זהירות',
    error: 'אוי שיט',
  },

  ApplicationError: {
    unexpectedError: 'משהו התפוצץ',
    applicationError: 'תקלה באפליקציה',
    unknownApplicationErrorMsg: 'קרתה תקלה מוזרה.\nהצוות כבר על זה. תחזור הביתה או תצעק עלינו בתמיכה.',
    goToHomeScreen: 'חזרה הביתה',
    pageWasNotFound: '404 – הדף נעלם',
    pageProbablyWasDeletedOrMoved: 'כנראה מחקנו או הזזנו אותו',
    networkError: 'אין קליטה',
    networkErrorMsg: 'השרת נרדם או שהאינטרנט שלך מקרטע. תבדוק חיבור ותחזור.',
  },

  Errors: {},
};
